#!/bin/bash

set -e

BASE="$(dirname $0)/.."

if [ ! $(which brew) ]; then
    echo "-- Installing homebrew - a package manager for OS X"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "-- Updating homebrew package list"
brew update

echo "-- Upgrading homebrew package list"
brew upgrade

echo "-- Add tap for osx-cross/avr/arv-libc"
brew tap osx-cross/avr

echo "-- Add tap for homebrew/cask-drivers"
brew tap homebrew/cask-drivers

echo "-- Installing required homebrew packages, this may take a while"
set +e
brew install $(sed 's/#.*//;/^$/d' $BASE/util/macos-packages.txt)
set -e

echo "-- Updating submodules"
git submodule sync
git submodule update --init --recursive
