#!/bin/bash

set -e

echo "-- Updating submodules"
git submodule sync
git submodule update --init --recursive

if [ ! $(which brew) ]; then
    echo "-- Installing homebrew - a package manager for OS X"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

BASE="$(dirname $0)/.."

echo "-- Add reqired taps"
brew tap osx-cross/avr
brew tap homebrew/cask-drivers

echo "-- Installing required homebrew packages"
set +e
brew update
brew install $(sed 's/#.*//;/^$/d' $BASE/util/macos-packages.txt)
set -e
