#!/bin/bash -e

HELP_STR="Usage: ./ubuntu-setup [-y | --yes] [-n | --noclobber] [-c | --clobber] [-f | --firmware] [-nf | --nofirmware] [-osl | --overwrite-sources-list ] [-h | --help]

\tyes:\t\t\tassume no user input
\tnoclobber:\t\tdont install 3rd party repositories
\tclobber:\t\tInstall 3rd party repositories
\tfirmware:\t\tInstall firmware repository
\tnofirmware:\t\tPrevents installation of firmware deps firmware repository
\toverwrite-sources-list:\tOverwrites the sources.list with gatech mirrors for faster ubuntu-setup. Only works on ubuntu > precise.
\thelp:\t\t\tprint this message!

This script will need root privileges"

# defaults!
OVERWRITE_SOURCES=false
YES=false

# parse command line args
for i in "$@"
do
    case $i in
        -y|--yes)
            YES=true
            ;;
        -h|--help)
            echo -e "$HELP_STR"
            exit 1
            ;;
        *)
            echo "Unrecognized Option: $i"
            echo -e "\n$HELP_STR"
            exit 1
            # unknown options
            ;;
    esac
done

# Become root
if [ $UID -ne 0 ]; then
	echo "-- Becoming root"
	exec sudo $0 $@
fi

apt-get update

# unset DPKG_FLAGS

BASE=$(readlink -f $(dirname $0)/..)

echo "-- Installing required packages"

# if yes option is checked, add  a -y
ARGS=""
if $YES; then
    ARGS="-y"
fi

PACKAGES="$(sed 's/#.*//;/^$/d' $BASE/util/ubuntu-packages.txt)"

# install all of the packages listed in required_packages.txt
apt-get install $ARGS $PACKAGES

# install python3 requirements
pip3 install -r $BASE/util/requirements3.txt

# ask for permission to install conan config
echo "About to install RJ Conan config profile. Needed to compile but will overwrite pre-existing conan remotes"
read -r -p "Is this okay? [y/N] " response
case "$response" in
[yY][eE][sS]|[yY])
        ;;
*)
        echo "Exiting without configuring Conan"
        echo "-- exit"
        exit 1
        ;;
esac


echo "-- Updating submodules"
git submodule sync
git submodule update --init --recursive

SETUP_USER="$SUDO_USER"
if [ -z "$SETUP_USER" ]; then
    SETUP_USER="$(whoami)"
fi

# TODO Should be changed to master one it has these changes
su $SETUP_USER -c 'conan config install --type git -sf util/conan-config/ https://github.com/RoboJackets/mtrain-firmware.git
'
