name: Pull request checks

on: [ pull_request ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo ./util/ubuntu-setup
    - name: make kicker
      run: make kicker
    - name: make control
      run: make control
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo ./util/macos-setup
      - name: make kicker
        run: make kicker
      - name: make control
        run: make control
