name: Pull request checks

on: [ pull_request ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo ./util/ubuntu-setup
    - name: make kicker
      run: make kicker
    - name: make kicker-test
      run: make kicker-test
    - name: make control
      run: make control
    - name: make control-tests
      run: make control-tests
    - name: make mtrain and its tests
      run: cd control/mtrain/ && make mtrain
    - name: make docs
      run: make docs
  style:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install dependencies
      run: sudo ./util/ubuntu-setup && sudo apt install python3-pip && pip install flake8-diff
    - name: Make ${{ github.base_ref }} and ${{ github.head_ref }} branches exist
      run: |
          git checkout -b ${{ github.base_ref }} --track origin/${{ github.base_ref }}
          git checkout -
          git checkout -b ${{ github.head_ref }}
          git checkout -
    - name: run style on all changed files
      run: |
          git diff -U0 --no-color ${{ github.base_ref }} ${{ github.head_ref }} | python3 util/style/clang-format-diff.py -binary clang-format-10 -i -p1
          git diff -U0 --no-color ${{ github.base_ref }} ${{ github.head_ref }} | black . --exclude "control/mtrain/"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        skip_checkout: true
        skip_fetch: true
        commit_message: Automatic style
        create_branch: false
        commit_options: '--no-verify --signoff'
    - name: Run clang-format
      run: |
          echo "::add-matcher::util/style/clang-format.json"
          git diff -U0 --no-color ${{ github.base_ref }} ${{ github.head_ref }} | python3 util/style/clang-format-diff.py -binary clang-format -p1 -dry_run
          echo "::remove-matcher owner=clang-format::"
    - name: Run flake8
      if: always()
      run: |
          echo "::add-matcher::util/style/flake8.json"
          find /usr/ | grep flake8
          flake8-diff --standard-flake8-output --vcs git ${{ github.base_ref }}
          echo "::remove-matcher owner=flake8-error::"
          echo "::remove-matcher owner=flake8-warning::"
